### ISSUE TITLE
Screenshot broken in Nova extension viewer

### ISSUE THREAD

**Issue by gingerbeardman** [jacobyard/Soot.novaextension#1]
<img width="1312" alt="Screen shot 2024-10-04 at 09 11 57" src="https://github.com/user-attachments/assets/1f57c9bd-4803-43cc-bda5-14b98df2a0a1">

**Comment by jacobyard** [comment]
Thankyou @gingerbeardman 
New to Nova extensions!
Aware of the issue, hope for it to be updated soon.

**Comment by jacobyard** [comment]
![CleanShot 2024-10-08 at 23 22 22@2x](https://github.com/user-attachments/assets/0075738d-0206-42f7-8e4b-e0dd199ccc16)
